name: Life of LY
url: http://jaasly.github.io


permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

categories_path : /categories.html
tags_path : /tags.html

JB :
  version : 0.3.0


exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']